### ISSUE TITLE
Search over the author field

### ISSUE THREAD

**Issue by dkobak** [bmschmidt/pubmed-explorer#60]
What would be really cool to have is to allow search over authors in addition to titles and journals. Ideally the full author list string. Rita does not have it parsed out, so this would need to wait, but eventually would be very cool, so I'm just going to leave it here.

**Comment by bmschmidt** [comment]
I have author parsing pretty well done in my pass at the pubmed code. The issue for me is that there are a lot of authors on papers, so including them will really balloon up the file size. This isn't as bad as it sounds, because we don't actually *have* to include the authors in the files--we could only load them later, when someone starts searching, as a separate set of columns. But that would require making some modifications to deepscatter (which are in my road map anyway)
