### ISSUE TITLE
More information about search results

### ISSUE THREAD

**Issue by slowkow** [bmschmidt/pubmed-explorer#61]
Could I ask if it is possible to enable regex so we can use word boundaries `\b` in our queries?

Is it possible to display the number of hits for a search query? (Maybe something like `123 results from 21M total articles`)

Could we see a small table of results? This might help to instantly disambiguate hits for queries like "hla" that include papers about "chlamydia" and "HLA-DRB1".

By the way, absolutely amazing job. This project is a gem 💎 and an inspiration! I hope to learn from your work.

**Comment by bmschmidt** [comment]
Thanks!

On number of hits and a small table of results (where you could click to zoom in or something)--yeah, this is a good idea! And not too hard.

So yeah, this is a bare bones search right now. the details--which I should really blog somewhere but will put here for the time being--are that search on Apache Arrow string columns is crazy slow. So pretty much all good pattern matching things, including regex, are impossible because we're not actually searching on words--we're turning the words in a Uint8 typed array, and then looking for occurrences of that array in the huge block of memory where Arrow stores tens of thousands of titles end-to-end. [https://github.com/bmschmidt/pubmed-explorer/blob/main/src/lib/stringsearch.ts] At some point I may enable case-sensitive search on the 26 English letters, but anything else would be even crazier than what I've done.

What's really needed is a regex library that runs on Uint8 arrays in Javascript (or, more likely, in wasm.) I suspect this isn't impossible, but I've never been able to find it.

**Comment by dkobak** [comment]
Oh so I was actually misleading everybody when I mentioned regexps in my Twitter thread. You had it implemented differently at first, and that supported regexps, and I did not realize that it does not work anymore.

What exactly is supported in the search right now? Is it case-insensitive? What happens if I type multiple words? Do I need to put quotes around them?

> On number of hits and a small table of results (where you could click to zoom in or something)--yeah, this is a good idea! And not too hard.

Isn't search currently performed only on shown papers? So number of hits would only reflect the number of hits among currently displayed papers (<< 21M)?

**Comment by bmschmidt** [comment]
Yes sorry I switched from server-side regex to client-side string matching last month.
This is just case-sensitive byte matching. So the query string `off topic` will match an article titled `the Kleptikoff topical ointment method`, but not an article titled `Off topic: bad posts in biomedicine`. If I get a chance I will manually build in some case-insensitive things.

And yes, search is performed only on loaded papers (which is a very slightly different number from *shown* papers). One of the nice things about result counts is that would make this feedback more explicit to users.


This way is a lot faster and scales better, but is less powerful.

**Comment by slowkow** [comment]
> Arrow stores tens of thousands of titles end-to-end

Have you considered trying to build a search index with a library like this? https://github.com/nextapps-de/flexsearch

The flexsearch library allows exporting an index so it can be downloaded by users later.

Just an idea! I don't know if it would work well in practice.

**Comment by bmschmidt** [comment]
Thanks @slowkow Any search index that requires building a second copy of the data is not ideal for me because of the sizes we're talking about here. Fortunately there's not actually a huge benefit to classic inverted index searches on this data, because most of what those offer is fine-tuning for relevance ranking, and in this viz we don't really care about what shows up first on the list and what's third--just hit/no hit is all that matters.

**Comment by bmschmidt** [comment]
I ran an experiment over the weekend having chat-GPT write me a little rust crate that compiles to wasm and consumes exactly the format of arrow string columns--it seems surprisingly good so far! The last roadblock is getting it bundled up with svelte-kit.

**Comment by bmschmidt** [comment]
If that comes in at a reasonable speed--let's say within 1/10 as fast as the current implementation--we would be able to use exactly the same search setup, but have full-on regex again.

**Comment by bmschmidt** [comment]
OK, I think this rust thing is actually working. These are wild times. Definitely slower than pure javascript byte-matching, but not much... Here's a regex capturing article titles that end with a question mark.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/1110758/232667360-6b45d1bd-5824-4ad8-83a4-5496dc0c3a2a.png">

**Comment by dkobak** [comment]
This sounds really cool! Is it already live?

**Comment by ritagonmar** [comment]
That is super nice!

**Comment by bmschmidt** [comment]
Yep it's live!

**Comment by bmschmidt** [comment]
Gotta figure out how to make it not-ugly and a little more dynamic before I push it up, but here's proof-of-concept for search results with click to go to both pubmed and to zoom-to-results. <img width="1475" alt="image" src="https://user-images.githubusercontent.com/1110758/233389573-e2d95b5d-2e5c-4763-bea0-b40c2663a739.png">

**Comment by bmschmidt** [comment]
I've pushed up a version that includes real search results which update in realtime to only include items inside the viewport.


<img width="1419" alt="image" src="https://user-images.githubusercontent.com/1110758/233829895-b2200506-afbc-4dd6-b007-dda58337064e.png">

**Comment by dkobak** [comment]
This is super cool!
